### ISSUE TITLE
Angular 7 cannot find the module

### ISSUE THREAD

**Issue by anelad** [Albejr/ngx-newsticker#2]
- [x ] bug report
- [ ] feature request
- [ ] proposal

#### What is the expected behavior?
Angular 7 should find the module

#### Current behavior:
Angular 7 cannot find the module

#### Error Message:
```
ERROR in app/app.module.ts(24,5): Error during template compile of 'AppModule'
  Could not resolve ngx-newsticker-albe relative to [object Object]..
src/app/app.module.ts(10,41): error TS2307: Cannot find module 'ngx-newsticker-albe'.
```

#### Steps to reproduce:
`npm i --save ngx-newsticker-albe` which installs v 2.1.0
then add module
```
...
import { NgxNewstickerAlbeModule } from 'ngx-newsticker-albe';
...

@NgModule({
...
...
  imports: [
    BrowserModule,
    AppRoutingModule,
    NgxNewstickerAlbeModule
  ],
...
...
})
export class AppModule { }
```

#### Which versions of package?
>2.1.0

**Comment by Albejr** [comment]
A versão "2.1.0" está atualizada para o Angular 8, tente a version "2.0.0".

**Comment by Albejr** [comment]
The "2.1.0" version is updated to Angular 8, try the "2.0.0" version.

**Comment by anelad** [comment]
@Albejr, I see that; so first I downgraded to 2.0.0 with the same result. Then updated the project to Angular 8 and tried with version 2.1.0, still the same. And I did not forget to restart the virtual server. It's weird.

**Comment by Albejr** [comment]
There was a problem publishing.
Version update (2.1.3).
TKS
