### ISSUE TITLE
background for counter

### ISSUE THREAD

**Issue by geno-github** [Albejr/ngx-newsticker#3]
#### I'm submitting a ...

- [X] bug report
- [ ] feature request
- [ ] proposal

#### What is the expected behavior?
Setting backColor should set the background color for all elements.

#### Current behavior:
The counter background does not change as expected.

#### Error Message:
none

#### Steps to reproduce:
Set backColor on module tag.

#### Which versions of package?
2.1.3

#### Other information:
The root cause of the issue is that the AfterViewInit event fires before the *ngIf for showCounter is resolved to true, therefore the ntCounterRef resolves to undefined and the style is not set.  I intend to submit a PR to resolve.

**Comment by Albejr** [comment]
TKS
