### ISSUE TITLE
sanitize html warning

### ISSUE THREAD

**Issue by jkon** [Albejr/ngx-newsticker#7]
#### I'm submitting a ...

- [ x ] bug report
- [ ] feature request
- [ ] proposal

#### What is the expected behavior?
Describe your issue here.
should be able to pass html content as strings to events input and have no html sanitize warnings in the console

#### Current behavior:
passing a string with html (I just added a <span> with a class around some text) results in a warning message in the console everytime the event changes (error message below)

The interesting thing is, the class is still there in the html and is being applied, so it's not a huge issue, just annoying as it will fill up the console and make it hard to find other things,

#### Error Message:
```
Copy the error message

core.js:6951 WARNING: sanitizing HTML stripped some content, see http://g.co/ng/security#xss
```

#### Steps to reproduce:
add a simple string with a span around it with a class on the span

#### Which versions of package?
>^2.1.3

**Comment by jkon** [comment]
Okay, this is weird. I changed the class to be dynamic. I have the whole thing in a template string and the class is like this now: ``` `<span class="${ change > 0 ? 'up' : change === 0 ? '' : 'down' }">...` ``` 
before it was like this: ``` `<span class="up">...` ```
the weird thing is, the warning is gone. I have no idea why this would change the way the string itself is passed into the innerHtml. 
You could close this if you want, but it might be interesting to look into

**Comment by Albejr** [comment]
Anyway, I will evaluate. 
Thanks!
