### ISSUE TITLE
Ability to have rendered html in the title

### ISSUE THREAD

**Issue by jkon** [Albejr/ngx-newsticker#8]
#### I'm submitting a ...

- [ ] bug report
- [x ] feature request
- [ ] proposal

#### What is the expected behavior?
Would be nice to be able to pass html into the title, maybe as a TemplateRef? Specifically, I want to add an icon that can have a popover opened on clicking the icon. Right now, I have added one by using an absolute positioning and a z-index, but I have other elements that expand and collapse that cause some issues using that method. It's really not a great solution. 

#### Current behavior:
title can only be passed as a string and displayed explicitly

**Comment by Albejr** [comment]
This new version implement "DomSanitizer". Now you can use it like this:

`<ngx-newsticker [title]="htmlTitle"`

![image](https://user-images.githubusercontent.com/24717256/93512605-ea9ea780-f8fa-11ea-83a5-2f4d7b40a555.png)

Result:
![image](https://user-images.githubusercontent.com/24717256/93512665-02762b80-f8fb-11ea-8d81-a012bb121bcf.png)
https://stackblitz.com/edit/ngx-newsticker-albe

TemplateRef will be implemented in the future. (sorry for the long wait.)
